### ISSUE TITLE
Template added to inbox after each use

### ISSUE THREAD

**Issue by chaselivingston** [dansays/thingy#4]
Each time I create a new draft and click the "+Add" button on the Thingy keyboard, I get the alert as expected for a first-time use, and then the example draft gets added to my inbox. Is it possible to have that only happen on the first run, and not appear after each subsequent use?

**Comment by dansays** [comment]
Whenever you run the task, it looks for a draft note titled "Thingy Autotagger Rules". Are you renaming the document?

**Comment by chaselivingston** [comment]
Ahh I see, I had been deleting that instead of archiving it not knowing the logic behind that. I'll archive it now so I suppose this shouldn't be an issue any longer.

**Comment by dansays** [comment]
Yeah, you can archive it if you don't want it in the way.
